# Generated by Django 2.2.6 on 2019-10-18 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=4, null=True, verbose_name='carro')),
                ('tipo', models.CharField(blank=True, choices=[('CMC_LUZ', 'CMC_LUZ'), ('CR1_LUZ', 'CR1_LUZ'), ('CR2_LUZ', 'CR2_LUZ'), ('CM_LUZ ', 'CM_LUZ '), ('CMC_EST', 'CMC_EST'), ('CR1_EST', 'CR1_EST'), ('CR2_EST', 'CR2_EST'), ('CM_EST ', 'CM_EST ')], max_length=7, null=True, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'carro',
                'verbose_name_plural': 'carros',
            },
        ),
        migrations.CreateModel(
            name='Trem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tue', models.CharField(blank=True, max_length=4, null=True, verbose_name='tue')),
            ],
            options={
                'verbose_name': 'TUE',
                'verbose_name_plural': 'TUEs',
            },
        ),
        migrations.CreateModel(
            name='Falha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm', models.CharField(blank=True, max_length=6, null=True, verbose_name='osm')),
                ('saf', models.CharField(blank=True, max_length=6, null=True, verbose_name='saf')),
                ('descricao', models.CharField(blank=True, max_length=300, null=True, verbose_name='descricao')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='horário')),
                ('ocorrencia', models.CharField(blank=True, max_length=300, null=True, verbose_name='ocorrência')),
                ('carros', models.ManyToManyField(blank=True, to='core.Carro', verbose_name='carros')),
                ('trem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='falhas', to='core.Trem', verbose_name='trem')),
            ],
            options={
                'verbose_name': 'falha',
                'verbose_name_plural': 'falhas',
            },
        ),
        migrations.AddField(
            model_name='carro',
            name='trem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='carros', to='core.Trem', verbose_name='trem'),
        ),
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=300, null=True, verbose_name='descricao')),
                ('data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='horário')),
                ('funcionarios', models.CharField(blank=True, max_length=300, null=True, verbose_name='funcionarios')),
                ('empresas', models.CharField(blank=True, max_length=300, null=True, verbose_name='empresas')),
                ('falha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atuacao', to='core.Falha', verbose_name='falha')),
                ('trem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atuacao', to='core.Trem', verbose_name='trem')),
            ],
        ),
    ]
