# Generated by Django 2.2.6 on 2019-10-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191018_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atuacao',
            options={'verbose_name': 'atuação', 'verbose_name_plural': 'atuações'},
        ),
    ]
